version: "3"

services:
  db:
    image: postgres:9.6-alpine
    restart: always
    env_file:
      - ./.docker/.env
    ports:
      - "5499:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/db-data
    networks:
      - symfony
  php:
    build:
      context: ./.docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - .:/var/www/symfony/
    networks:
      - symfony
  nginx:
    build:
      context: ./.docker/nginx
    volumes:
      - .:/var/www/symfony/
    ports:
      - 8099:80
    networks:
      - symfony
    env_file:
      - ./.docker/.env.nginx.local
volumes:
  symfony_dockerized_app_sync:
  db_app:
  db-data:

networks:
  symfony:
