version: "3.5"

services:
  db:
    image: postgres:15.2-alpine
    restart: on-failure
    env_file:
      - ./.docker/.env
    ports:
      - "5498:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/db-data
  php:
    build:
      context: ./.docker/php

    env_file:
        - ./.docker/.env
    volumes:
      - .:/var/www/app/
    restart: on-failure
  nginx:
    build:
      context: ./.docker/nginx
    volumes:
      - .:/var/www/app/
    ports:
      - 8099:80
    env_file:
      - ./.docker/.env.nginx.local
    restart: on-failure
volumes:
  app_sync:
  db_app:
  db-data:
