name: Deploy starting
on:
  push:
    tags:

permissions:
  contents: read

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update package manager
        run: sudo apt update -y
